### ISSUE TITLE
websocket

### ISSUE THREAD

**Issue by 810961186** [burakoner/OKX.Api#37] opened 2023-08-09 15:01 UTC
use private channel subscribe back {"Data":null,"Raw":null,"Error":{"Code":null,"Message":"Authentication failed: No credentials provided for private endpoint","Data":null},"Success":false}

**Comment by burakoner** [comment] 2023-08-09 20:44
Did you provide your API credentials?

**Comment by 810961186** [comment] 2023-08-10 07:37
yes，I wrote it like this：
  var ws = new OKXWebSocketApiClient();
            ws.SetApiCredentials("XXX", "XXX", "XXX");          
            var response=await ws.OrderBookTrading.Trade.SubscribeToOrderUpdatesAsync((data) =>
            {
                if (data != null)
                {
                    Console.WriteLine($"{DateTime.Now.ToString("HH:mm:ss")}:{JsonConvert.SerializeObject(data)}");
                    // ... Your logic here
                }
            }, OkxInstrumentType.Any, "", "");
            Console.WriteLine($"{DateTime.Now.ToString("HH:mm:ss")}:{JsonConvert.SerializeObject(response)}");
response is {"Data":null,"Raw":null,"Error":{"Code":null,"Message":"Authentication failed: No credentials provided for private endpoint","Data":null},"Success":false}

**Comment by HH-T** [comment] 2023-09-13 03:36
same result.  How to fix it?

**Comment by burakoner** [comment] 2023-09-16 08:01
The problem is completely different. I tried many times, there is no problem with login. But problem is related with your request. Even API docs says some parameters is optional, websocket returns message below

`{
"event":"error",
"msg":"channel:orders,instType:ANY,instFamily:,instId: doesn't exist",
"code":"60018"
}`

I've fixed this situation, it shows correct error response now. I'll release new version today.
I wont close this issue and wait for your response.
 
Thanks for feedback.

**Closed** 2023-09-18 22:04 UTC
